title: Blog about nothing
author: Ben Yee
email: byee1@ocdsb.ca
description: > like stuff

github_username: EzPzLemonYeezy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot 
